<?php
$pageTitle='Student Form';require_once __DIR__.'/../includes/auth.php';requireAdmin();$db=getDB();
$id=(int)($_GET['id']??0);$student=null;
if($id){$stmt=$db->prepare("SELECT * FROM students WHERE id=?");$stmt->execute([$id]);$student=$stmt->fetch();if(!$student){setFlash('error','Not found.');header('Location: /admin/students.php');exit;}$pageTitle='Edit Student';}else{$pageTitle='Add Student';}
if($_SERVER['REQUEST_METHOD']==='POST'){if(!verifyCsrf()){setFlash('error','Invalid.');header("Location: /admin/student-form.php?id=$id");exit;}
$d=['admission_no'=>trim($_POST['admission_no']??''),'name'=>trim($_POST['name']??''),'father_name'=>trim($_POST['father_name']??''),'mother_name'=>trim($_POST['mother_name']??''),'dob'=>$_POST['dob']?:null,'gender'=>$_POST['gender']?:null,'class'=>$_POST['class']??'','section'=>$_POST['section']??'A','roll_no'=>$_POST['roll_no']?(int)$_POST['roll_no']:null,'phone'=>trim($_POST['phone']??''),'email'=>trim($_POST['email']??''),'address'=>trim($_POST['address']??''),'photo'=>null,'blood_group'=>$_POST['blood_group']??'','category'=>$_POST['category']??'','aadhar_no'=>trim($_POST['aadhar_no']??''),'status'=>$_POST['status']??'active','admission_date'=>$_POST['admission_date']?:null];
$photo=$student['photo']??null;
if(!empty($_FILES['photo']['tmp_name'])){$allowed=['image/jpeg','image/png','image/webp'];if(in_array($_FILES['photo']['type'],$allowed)&&$_FILES['photo']['size']<=5*1024*1024){$ext=pathinfo($_FILES['photo']['name'],PATHINFO_EXTENSION);$fn='student_'.time().'_'.rand(1000,9999).'.'.$ext;$dir=__DIR__.'/../uploads/photos/';if(!is_dir($dir))mkdir($dir,0755,true);if(move_uploaded_file($_FILES['photo']['tmp_name'],$dir.$fn))$photo='/uploads/photos/'.$fn;}}
$d['photo']=$photo;
if(!$d['admission_no']||!$d['name']){setFlash('error','Admission No and Name required.');}else{try{if($id){$db->prepare("UPDATE students SET admission_no=?,name=?,father_name=?,mother_name=?,dob=?,gender=?,class=?,section=?,roll_no=?,phone=?,email=?,address=?,photo=?,blood_group=?,category=?,aadhar_no=?,status=?,admission_date=? WHERE id=?")->execute([...array_values($d),$id]);auditLog('update_student','student',$id);setFlash('success','Updated.');}else{$d['created_by']=currentUserId();$db->prepare("INSERT INTO students (admission_no,name,father_name,mother_name,dob,gender,class,section,roll_no,phone,email,address,photo,blood_group,category,aadhar_no,status,admission_date,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)")->execute(array_values($d));auditLog('create_student','student',(int)$db->lastInsertId());setFlash('success','Added.');}header('Location: /admin/students.php');exit;}catch(PDOException $e){if($e->getCode()==23000)setFlash('error','Admission no exists.');else setFlash('error',$e->getMessage());}}}
$s=$student??[];require_once __DIR__.'/../includes/header.php';
?>
<div class="card border-0 rounded-3"><div class="card-body"><form method="POST" enctype="multipart/form-data"><?=csrfField()?><div class="row g-3">
<div class="col-md-4"><label class="form-label">Admission No *</label><input type="text" name="admission_no" class="form-control" required value="<?=e($s['admission_no']??'')?>"></div>
<div class="col-md-4"><label class="form-label">Full Name *</label><input type="text" name="name" class="form-control" required value="<?=e($s['name']??'')?>"></div>
<div class="col-md-4"><label class="form-label">Gender</label><select name="gender" class="form-select"><option value="">Select</option><?php foreach(['male','female','other'] as $g):?><option value="<?=$g?>" <?=($s['gender']??'')===$g?'selected':''?>><?=ucfirst($g)?></option><?php endforeach;?></select></div>
<div class="col-md-4"><label class="form-label">Father's Name</label><input type="text" name="father_name" class="form-control" value="<?=e($s['father_name']??'')?>"></div>
<div class="col-md-4"><label class="form-label">Mother's Name</label><input type="text" name="mother_name" class="form-control" value="<?=e($s['mother_name']??'')?>"></div>
<div class="col-md-4"><label class="form-label">DOB</label><input type="date" name="dob" class="form-control" value="<?=e($s['dob']??'')?>"></div>
<div class="col-md-3"><label class="form-label">Class</label><select name="class" class="form-select"><?php for($i=1;$i<=12;$i++):?><option value="<?=$i?>" <?=($s['class']??'')==(string)$i?'selected':''?>><?=$i?></option><?php endfor;?></select></div>
<div class="col-md-3"><label class="form-label">Section</label><select name="section" class="form-select"><?php foreach(['A','B','C','D'] as $sec):?><option value="<?=$sec?>" <?=($s['section']??'A')===$sec?'selected':''?>><?=$sec?></option><?php endforeach;?></select></div>
<div class="col-md-3"><label class="form-label">Roll No</label><input type="number" name="roll_no" class="form-control" value="<?=e($s['roll_no']??'')?>"></div>
<div class="col-md-3"><label class="form-label">Status</label><select name="status" class="form-select"><?php foreach(['active','inactive','alumni','tc_issued'] as $st):?><option value="<?=$st?>" <?=($s['status']??'active')===$st?'selected':''?>><?=ucfirst($st)?></option><?php endforeach;?></select></div>
<div class="col-md-4"><label class="form-label">Phone</label><input type="tel" name="phone" class="form-control" value="<?=e($s['phone']??'')?>"></div>
<div class="col-md-4"><label class="form-label">Email</label><input type="email" name="email" class="form-control" value="<?=e($s['email']??'')?>"></div>
<div class="col-md-4"><label class="form-label">Admission Date</label><input type="date" name="admission_date" class="form-control" value="<?=e($s['admission_date']??'')?>"></div>
<div class="col-md-3"><label class="form-label">Blood Group</label><select name="blood_group" class="form-select"><option value="">Select</option><?php foreach(['A+','A-','B+','B-','O+','O-','AB+','AB-'] as $bg):?><option value="<?=$bg?>" <?=($s['blood_group']??'')===$bg?'selected':''?>><?=$bg?></option><?php endforeach;?></select></div>
<div class="col-md-3"><label class="form-label">Category</label><input type="text" name="category" class="form-control" value="<?=e($s['category']??'')?>" placeholder="General, OBC..."></div>
<div class="col-md-3"><label class="form-label">Aadhar</label><input type="text" name="aadhar_no" class="form-control" maxlength="12" value="<?=e($s['aadhar_no']??'')?>"></div>
<div class="col-md-3"><label class="form-label">Photo</label><input type="file" name="photo" class="form-control" accept="image/*"><?php if(!empty($s['photo'])):?><small class="text-muted"><?=e(basename($s['photo']))?></small><?php endif;?></div>
<div class="col-12"><label class="form-label">Address</label><textarea name="address" class="form-control" rows="2"><?=e($s['address']??'')?></textarea></div>
<div class="col-12 d-flex gap-2"><button type="submit" class="btn btn-primary"><i class="bi bi-check-lg me-1"></i><?=$id?'Update':'Add'?></button><a href="/admin/students.php" class="btn btn-outline-secondary">Cancel</a></div>
</div></form></div></div>
<?php require_once __DIR__.'/../includes/footer.php';?>
